version: "3.6"

services:
  maci:
    tty: true
    image: maci
    network_mode: "host"
    volumes:
      - ./zkeys:/root/maci/cli/zkeys
      - ./proofs:/root/maci/cli/proofs
      - ./docker/defaults.ts:/root/maci/cli/ts/defaults.ts
      - ./docker/defaults.js:/root/maci/cli/build/defaults.js
