version: "3.6"

services:
  maci:
    tty: true
    image: maci
    network_mode: "host"
    working_dir: /root/maci/cli
    volumes:
      - ./zkeys:/root/maci/cli/zkeys
      - ./proofs:/root/maci/cli/proofs
